FROM ubuntu:24.04
RUN apt-get update && apt-get install -y curl ca-certificates lsb-release locales sudo libfuse2 libgl1-mesa-dri libgl1-mesa-glx mesa-vulkan-drivers libvulkan1 && rm -rf /var/lib/apt/lists/*
RUN locale-gen en_US.UTF-8
RUN useradd -m -s /bin/bash sliceruser && echo "sliceruser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER sliceruser
WORKDIR /home/sliceruser
